### ISSUE TITLE
Unable to install the pod

### ISSUE THREAD

**Issue by veereshb9** [streem/streem-sdk-ios#30]
[!] Unable to find a specification for `RxAnimated (~> 0.7.0)` depended upon by `StreemKit`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by dgoldman-pdx** [comment]
@veereshb9 have you already tried running `pod repo update` or `pod install --repo-update`, as suggested?

**Comment by dgoldman-pdx** [comment]
@veereshb9 any news?
